# Generated by Django 5.2.6 on 2025-09-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=10)),
                ('documento', models.CharField(blank=True, default='', max_length=32)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('producto', models.CharField(blank=True, default='', max_length=32)),
                ('poliza', models.CharField(blank=True, default='', max_length=64)),
                ('periodo', models.CharField(blank=True, default='', max_length=4)),
                ('valor_asegurado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_prima', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('doc_cobro', models.CharField(blank=True, default='', max_length=64)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('telefono_1', models.CharField(blank=True, default='', max_length=32)),
                ('telefono_2', models.CharField(blank=True, default='', max_length=32)),
                ('telefono_3', models.CharField(blank=True, default='', max_length=32)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('departamento', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_trans', models.CharField(blank=True, default='', max_length=8)),
                ('beneficiarios', models.TextField(blank=True, default='')),
                ('genero', models.CharField(blank=True, default='', max_length=4)),
                ('sucursal', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_cuenta', models.CharField(blank=True, default='', max_length=32)),
                ('ultimos_digitos_cuenta', models.CharField(blank=True, default='', max_length=32)),
                ('entidad_bancaria', models.CharField(blank=True, default='', max_length=64)),
                ('nombre_banco', models.CharField(blank=True, default='', max_length=120)),
                ('estado_debito', models.CharField(blank=True, default='', max_length=32)),
                ('causal_rechazo', models.CharField(blank=True, default='', max_length=120)),
                ('codigo_canal', models.CharField(blank=True, default='', max_length=8)),
                ('descripcion_canal', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_estrategia', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_estrategia', models.CharField(blank=True, default='', max_length=64)),
                ('correo_electronico', models.EmailField(blank=True, default='', max_length=254)),
                ('fecha_entrega_colmena', models.DateField(blank=True, null=True)),
                ('mes_a_trabajar', models.CharField(blank=True, default='', max_length=2)),
                ('nombre_db', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.BooleanField(default=False)),
                ('whatsapp', models.BooleanField(default=False)),
                ('texto', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('fisica', models.BooleanField(default=False)),
                ('mejor_canal', models.CharField(blank=True, default='', max_length=20)),
                ('contactar_al', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
